android.experimental.enableNewResourceShrinker.preciseShrinking=true
android.enableAppCompileTimeRClass=true
android.useAndroidX=true

KEYSTORE_FILE=key.jks
KEYSTORE_PASSWORD=kuyang123
KEY_ALIAS=kuyang
KEY_PASSWORD=kuyang123

org.gradle.parallel=true
org.gradle.vfs.watch=true
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m
org.gradle.caching=true
android.native.buildOutput=verbose
